import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'app_colors.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FThemeData get redLight {
  final baseTheme = FThemes.red.light;

  final customSelectFieldStyle = baseTheme.selectStyle.selectFieldStyle.copyWith(
    filled: true,
    fillColor: AppColors.brandPrimary,
    contentTextStyle: FWidgetStateMap.all(const TextStyle(color: Colors.white, fontWeight: FontWeight.w500)),
    hintTextStyle: FWidgetStateMap.all(const TextStyle(color: Colors.white)),
  );

  return FThemeData(
    colors: baseTheme.colors.copyWith(primary: AppColors.brandPrimary),
    typography: _typography(colors: baseTheme.colors, defaultFontFamily: 'BeVietnamPro'),
    style: baseTheme.style,
    selectStyle: baseTheme.selectStyle.copyWith(
      selectFieldStyle: customSelectFieldStyle, // ignore: implicit_call_tearoffs
      iconStyle: const IconThemeData(color: Colors.white, size: 18),
    ),
  );
}

FThemeData get redDark {
  final baseTheme = FThemes.red.dark;

  final customSelectFieldStyleDark = baseTheme.selectStyle.selectFieldStyle.copyWith(
    filled: true,
    fillColor: AppColors.brandPrimary,
    contentTextStyle: FWidgetStateMap.all(const TextStyle(color: Colors.white, fontWeight: FontWeight.w500)),
    hintTextStyle: FWidgetStateMap.all(const TextStyle(color: Colors.white)),
  );

  return FThemeData(
    colors: baseTheme.colors.copyWith(primary: AppColors.brandPrimary),
    typography: _typography(colors: baseTheme.colors, defaultFontFamily: 'BeVietnamPro'),
    style: baseTheme.style,
    selectStyle: baseTheme.selectStyle.copyWith(
      selectFieldStyle: customSelectFieldStyleDark, // ignore: implicit_call_tearoffs
      iconStyle: const IconThemeData(color: Colors.white, size: 18),
    ),
  );
}

FTypography _typography({
  required FColors colors,
  String defaultFontFamily = 'packages/forui/Inter',
}) => FTypography(
  xs: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 12,
    height: 1,
  ),
  sm: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 14,
    height: 1.25,
  ),
  base: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 16,
    height: 1.5,
  ),
  lg: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 18,
    height: 1.75,
  ),
  xl: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 20,
    height: 1.75,
  ),
  xl2: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 22,
    height: 2,
  ),
  xl3: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 30,
    height: 2.25,
  ),
  xl4: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 36,
    height: 2.5,
  ),
  xl5: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 48,
    height: 1,
  ),
  xl6: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 60,
    height: 1,
  ),
  xl7: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 72,
    height: 1,
  ),
  xl8: TextStyle(
    color: colors.foreground,
    fontFamily: defaultFontFamily,
    fontSize: 96,
    height: 1,
  ),
);

